import CryptoKit
import CtrlxCommon
import Dependencies
import DependenciesMacros
import Foundation

/// A per-new-shell integration, not an alias installed into user dotfiles.
/// zsh reads the user's original startup files normally. A one-shot precmd
/// installs the function AFTER aliases/functions/PATH have been configured.
enum TerminalAgentShellIntegration {
    static func supports(shell: String) -> Bool {
        (shell as NSString).lastPathComponent == "zsh"
    }

    /// Evaluated by tmux's command shell before execing the user's login shell.
    /// Preserve unset versus set ZDOTDIR, including the E2E history-isolation shim.
    static func launchPrefix(directory: String) -> String {
        "if [ \"${ZDOTDIR+x}\" = x ]; then "
            + "export CTRLX_SHELL_ORIGINAL_ZDOTDIR=\"$ZDOTDIR\"; "
            + "else unset CTRLX_SHELL_ORIGINAL_ZDOTDIR; fi; "
            + "export ZDOTDIR=\(directory.posixSingleQuoted); "
    }

    static func zshEnvironment(arguments: [String]) -> String {
        let defaults = arguments.map(\.posixSingleQuoted).joined(separator: " ")
        return #"""
        # Generated by CtrlX. No user dotfiles are changed.
        if [[ ${CTRLX_SHELL_ORIGINAL_ZDOTDIR+x} == x ]]; then
            export ZDOTDIR="$CTRLX_SHELL_ORIGINAL_ZDOTDIR"
        else
            unset ZDOTDIR
        fi
        unset CTRLX_SHELL_ORIGINAL_ZDOTDIR
        if [[ -r ${ZDOTDIR-$HOME}/.zshenv ]]; then
            source "${ZDOTDIR-$HOME}/.zshenv"
        fi

        if [[ -o interactive ]]; then
            function __ctrlx_install_codex_telemetry() {
                # Preserve all user prompt hooks, and run only once per shell.
                precmd_functions=("${(@)precmd_functions:#__ctrlx_install_codex_telemetry}")
                if (( ! ${+aliases[codex]} && ! ${+functions[codex]} )); then
                    function codex() {
                        # Explicit OTEL config (including UI launches) wins as
                        # a whole: never duplicate defaults or partially merge
                        # a user's own exporter with CtrlX's local endpoint.
                        local ctrlx_arg ctrlx_key ctrlx_previous=''
                        for ctrlx_arg in "$@"; do
                            [[ "$ctrlx_arg" == -- ]] && break
                            ctrlx_key=''
                            if [[ "$ctrlx_previous" == -c || "$ctrlx_previous" == --config ]]; then
                                ctrlx_key="$ctrlx_arg"
                            else
                                case "$ctrlx_arg" in
                                    --config=*) ctrlx_key="${ctrlx_arg#--config=}" ;;
                                    -c?*) ctrlx_key="${ctrlx_arg#-c}" ;;
                                esac
                            fi
                            ctrlx_key="${ctrlx_key%%=*}"
                            ctrlx_key="${ctrlx_key//[[:space:]]/}"
                            case "$ctrlx_key" in
                                otel|otel.*|\"otel\"|\"otel\".*|\'otel\'|\'otel\'.*)
                                    command codex "$@"
                                    return $? ;;
                            esac
                            ctrlx_previous="$ctrlx_arg"
                        done
                        command codex \#(defaults) "$@"
                    }
                fi
                unfunction __ctrlx_install_codex_telemetry
            }
            typeset -ga precmd_functions
            precmd_functions+=(__ctrlx_install_codex_telemetry)
        fi
        """# + "\n"
    }
}

@DependencyClient
struct TerminalAgentShellFiles: Sendable {
    var prepare: @Sendable (_ arguments: [String]) async throws -> String
}

extension TerminalAgentShellFiles: DependencyKey {
    static let liveValue = Self(prepare: { try await TerminalAgentShellFileStore.shared.prepare($0) })
}

/// Content-addressed, private startup files: concurrent new terminals with
/// different settings cannot overwrite each other's launch snapshot. No I/O
/// on the main actor and no dependency on an app-bundle path surviving updates.
actor TerminalAgentShellFileStore {
    static let shared = TerminalAgentShellFileStore(
        root: FileManager.default.temporaryDirectory.appendingPathComponent("ctrlx-shell-integration")
    )
    private let root: URL

    init(root: URL) { self.root = root }

    func prepare(_ arguments: [String]) throws -> String {
        let content = Data(TerminalAgentShellIntegration.zshEnvironment(arguments: arguments).utf8)
        let digest = SHA256.hash(data: content).map { String(format: "%02x", $0) }.joined()
        let directory = root.appendingPathComponent(digest, isDirectory: true)
        let file = directory.appendingPathComponent(".zshenv")
        let files = FileManager.default
        try files.createDirectory(at: directory, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
        if try !files.fileExists(atPath: file.path) || Data(contentsOf: file) != content {
            try content.write(to: file, options: .atomic)
            try files.setAttributes([.posixPermissions: 0o600], ofItemAtPath: file.path)
        }
        return directory.path
    }
}
